version: '3.8'

services:
  backend:
    build: ./backend
    container_name: kaiwa-backend
    ports:
      - "3000:3000"
    volumes:
      - kaiwa_db_data:/backend/database
    networks:
      - kaiwa_app_network
    environment:
      - DATABASE_PATH=/backend/database/database.db

  frontend:
    build: ./frontend
    container_name: kaiwa-frontend
    ports:
      - "80:80"
    depends_on:
      - kaiwa-backend
    networks:
      - kaiwa_app_network
    environment:
      - BACKEND_URL=http://kaiwa-backend:3001

volumes:
  kaiwa_db_data:

networks:
  kaiwa_app_network:
