---
- name: Alle Hosts zu den bekannten Hosts hinzuf端gen und Verbindung 端berpr端fen
  hosts: all
  gather_facts: false
  tasks:
    - name: Warte bis SSH erreichbar ist
      ansible.builtin.wait_for:
        port: 22
        host: "{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}"
        timeout: 60
        delay: 8
      delegate_to: localhost

    - name: F端ge Host zur known_hosts-Datei hinzu
      ansible.builtin.shell: ssh-keyscan -H {{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }} >> ~/.ssh/known_hosts
      delegate_to: localhost
      run_once: false

    - name: ping all hosts
      ansible.builtin.ping:
