---
- name: Jenkins Docker Node mit Java konfigurieren
  hosts: jenkins_docker_node
  become: true

  vars:
    docker_users:
      - ubuntu
      - jenkins

  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Docker installieren
      include_tasks: tasks/docker_setup.yml
      when: ansible_os_family == "Debian"

    - name: Install OpenJDK 17
      ansible.builtin.apt:
        name: openjdk-17-jre
        state: present
